# This rule is not used by the project kubevirt-migration-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to migrations.kubevirt.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-migration-controller
    app.kubernetes.io/managed-by: kustomize
  name: migplan-viewer-role
rules:
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - virtualmachinestoragemigrationplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - virtualmachinestoragemigrationplans/status
  verbs:
  - get
