# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/migrations.kubevirt.io_virtualmachinestoragemigrationplans.yaml
- bases/migrations.kubevirt.io_virtualmachinestoragemigrations.yaml
- bases/kubevirt.io_virtualmachineinstancemigrations.yaml
- bases/kubevirt.io_virtualmachineinstances.yaml
- bases/kubevirt.io_virtualmachines.yaml
- bases/kubevirt.io_virtualmachineinstancepresets.yaml
- bases/kubevirt.io_virtualmachineinstancereplicasets.yaml
- bases/kubevirt.io_kubevirts.yaml
- bases/cdi.kubevirt.io_datavolumes.yaml
- bases/cdi.kubevirt.io_cdiconfigs.yaml
- bases/cdi.kubevirt.io_cdis.yaml
- bases/cdi.kubevirt.io_datasources.yaml
- bases/cdi.kubevirt.io_volumeclonesources.yaml
- bases/cdi.kubevirt.io_storageprofiles.yaml
- bases/cdi.kubevirt.io_objecttransfers.yaml
- bases/cdi.kubevirt.io_volumeimportsources.yaml
- bases/cdi.kubevirt.io_volumeuploadsources.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
