---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: storageprofiles.cdi.kubevirt.io
spec:
  group: cdi.kubevirt.io
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: StorageProfile provides a CDI specific recommendation for storage
          parameters
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StorageProfileSpec defines specification for StorageProfile
            properties:
              claimPropertySets:
                description: ClaimPropertySets is a provided set of properties applicable
                  to PVC
                items:
                  description: ClaimPropertySet is a set of properties applicable
                    to PVC
                  properties:
                    accessModes:
                      description: |-
                        AccessModes contains the desired access modes the volume should have.
                        More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
                      items:
                        type: string
                      maxItems: 4
                      type: array
                      x-kubernetes-validations:
                      - message: Illegal AccessMode
                        rule: self.all(am, am in ['ReadWriteOnce', 'ReadOnlyMany',
                          'ReadWriteMany', 'ReadWriteOncePod'])
                    volumeMode:
                      description: |-
                        VolumeMode defines what type of volume is required by the claim.
                        Value of Filesystem is implied when not included in claim spec.
                      enum:
                      - Block
                      - Filesystem
                      type: string
                  required:
                  - accessModes
                  - volumeMode
                  type: object
                maxItems: 8
                type: array
              cloneStrategy:
                description: CloneStrategy defines the preferred method for performing
                  a CDI clone
                type: string
              dataImportCronSourceFormat:
                description: DataImportCronSourceFormat defines the format of the
                  DataImportCron-created disk image sources
                type: string
              snapshotClass:
                description: SnapshotClass is optional specific VolumeSnapshotClass
                  for CloneStrategySnapshot. If not set, a VolumeSnapshotClass is
                  chosen according to the provisioner.
                type: string
            type: object
          status:
            description: StorageProfileStatus provides the most recently observed
              status of the StorageProfile
            properties:
              claimPropertySets:
                description: ClaimPropertySets computed from the spec and detected
                  in the system
                items:
                  description: ClaimPropertySet is a set of properties applicable
                    to PVC
                  properties:
                    accessModes:
                      description: |-
                        AccessModes contains the desired access modes the volume should have.
                        More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
                      items:
                        type: string
                      maxItems: 4
                      type: array
                      x-kubernetes-validations:
                      - message: Illegal AccessMode
                        rule: self.all(am, am in ['ReadWriteOnce', 'ReadOnlyMany',
                          'ReadWriteMany', 'ReadWriteOncePod'])
                    volumeMode:
                      description: |-
                        VolumeMode defines what type of volume is required by the claim.
                        Value of Filesystem is implied when not included in claim spec.
                      enum:
                      - Block
                      - Filesystem
                      type: string
                  required:
                  - accessModes
                  - volumeMode
                  type: object
                maxItems: 8
                type: array
              cloneStrategy:
                description: CloneStrategy defines the preferred method for performing
                  a CDI clone
                type: string
              dataImportCronSourceFormat:
                description: DataImportCronSourceFormat defines the format of the
                  DataImportCron-created disk image sources
                type: string
              provisioner:
                description: The Storage class provisioner plugin name
                type: string
              snapshotClass:
                description: SnapshotClass is optional specific VolumeSnapshotClass
                  for CloneStrategySnapshot. If not set, a VolumeSnapshotClass is
                  chosen according to the provisioner.
                type: string
              storageClass:
                description: The StorageClass name for which capabilities are defined
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
